### PR TITLE
Update recommended version of language tool to 5.0

### PR DESCRIPTION
**Pull request by GegznaV**

### CODE REVIEW

**Comment by nevrome** [comment]
Thank you, @GegznaV! I think this package could actually go to CRAN. It's simple and stable.

**Comment by GegznaV** [comment]
I'm thinking of some additional functionality to detect all installed versions of LanguageTool and to delete unwanted/old versions of the tool. As well as the ability to detect the newest released version of the tool as well as ability to use other than the recommended version of the tool.

**Comment by nevrome** [comment]
Hm...

> detect all installed versions of LanguageTool and to delete unwanted/old versions of the tool. As well as the ability to detect the newest released version of the tool as well as ability to use other than the recommended version of the tool

I think that would be tricky and also rather obscure functionality. Why should you check a package for an `uninstall` function if you can just delete a folder? Sure - our convenient quick install function `lato_quick_setup()` uses the home directory as a default and we could keep track of LanguageTool folders, but what happens if a user wants to install somewhere else? 

`languagetool()` has the `executable` option to set any executable path. In my opinion that settles all of that. It allows the user to set the system up in any way she/he wants. That also allows to use different LanguageTool versions, as long as the CLI API is more or less stable.

I would say we leave things as they are and only test if we cover all options of LanguageTool v.5.0. The documentation and README should then include a sentence like "Tested only on v.5.0.". Every now and then we could do an update - just as you did with this PR. 

Some more unit tests for the output would be nice in that context. I think I will look at that now.

If you have time and energy and really want to write some new code, then we could try to get LanguageToolR to talk to LanguageTool Server setups :smile: . I guess that would require a completely different approach compared to the CLI interface we have now.

**Comment by GegznaV** [comment]
Ok, I was not clear enough. What I had in mind by saying `install` was the result of `lato_quick_setup()` (LanguageTool downloaded to the home directory). And by saying "uninstall" I meant that before downloading a new version of LanguageTool, the package should at least warn, if there is an older (or current) version of the tool and suggest deleting it.

**Comment by nevrome** [comment]
Ok - that sounds easy enough. Can you prepare a PR?

**Comment by GegznaV** [comment]
Sorry for non responding in time: I'm on vocation now.

**Pull request merged**
